baseURL = "https://mikeknowl.es/"
languageCode = "en-us"
title = "Mike Knowles"

assetDir = "assets"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
staticDir = "static"

enableEmoji = true

[build]
    writeStats = true